# Generated by Django 3.2.2 on 2021-05-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gre_score', models.IntegerField(blank=True, null=True)),
                ('toefl_score', models.IntegerField(blank=True, null=True)),
                ('sop_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lor_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('uni_score', models.IntegerField(blank=True, null=True)),
                ('research', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, max_length=1)),
                ('chance_of_admit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
