# Generated by Django 3.2.2 on 2021-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
