# Generated by Django 3.1.4 on 2021-01-13 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(default='avatar.svg', upload_to='profile_pics')),
                ('country', models.TextField(null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('gre_score', models.IntegerField(null=True)),
                ('toefl_score', models.IntegerField(null=True)),
                ('sop_score', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('lor_score', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('uni_score', models.IntegerField(null=True)),
                ('research', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
