# Generated by Django 3.1.4 on 2020-12-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201207_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
