# Generated by Django 3.1.4 on 2021-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210320_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=1),
        ),
    ]
