# Generated by Django 3.1.4 on 2021-01-10 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(default='college_finder_app\\components\\static\\img\\avatar.svg', upload_to='profile_pics')),
                ('country', models.TextField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gre_score', models.IntegerField()),
                ('toefl_score', models.IntegerField()),
                ('sop_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('lor_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('uni_score', models.IntegerField()),
                ('research', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
