# Generated by Django 3.1.4 on 2021-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210110_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to='profile_pics'),
        ),
    ]
