# Generated by Django 3.1.4 on 2021-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210321_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], max_length=1),
        ),
    ]
