# Generated by Django 3.1.4 on 2021-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210321_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, max_length=1),
        ),
    ]
