# Generated by Django 3.1.4 on 2021-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210322_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chance_of_admit',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
