# Generated by Django 3.1.4 on 2021-04-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_chance_of_admit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chance_of_admit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
