# Generated by Django 3.1.4 on 2021-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_order', models.IntegerField(max_length=4)),
                ('rank', models.TextField()),
                ('name', models.TextField()),
                ('scores_overall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_overall_rank', models.IntegerField(max_length=4)),
                ('scores_teaching', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_teaching_rank', models.IntegerField(max_length=4)),
                ('scores_research', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_research_rank', models.IntegerField(max_length=4)),
                ('scores_citations', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_citations_rank', models.IntegerField(max_length=4)),
                ('scores_industry_income', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_industry_income_rank', models.IntegerField(max_length=4)),
                ('scores_international_outlook', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scores_international_outlook_rank', models.IntegerField(max_length=4)),
                ('record_type', models.TextField()),
                ('member_level', models.IntegerField(max_length=4)),
                ('url', models.TextField()),
                ('nid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.TextField()),
                ('stats_number_students', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stats_student_staff_ratio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stats_pc_intl_students', models.TextField()),
                ('stats_female_male_ratio', models.TextField()),
                ('aliases', models.TextField()),
                ('subjects_offered', models.TextField()),
            ],
        ),
    ]
