# Generated by Django 3.1.4 on 2021-05-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='member_level',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='record_type',
        ),
    ]
