# Generated by Django 3.1.4 on 2021-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20210110_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='member_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='rank_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_citations_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_industry_income_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_international_outlook_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_overall_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_research_rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_teaching_rank',
            field=models.IntegerField(),
        ),
    ]
