# Generated by Django 3.1.4 on 2021-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20210110_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='stats_female_male_ratio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='stats_pc_intl_students',
            field=models.TextField(),
        ),
    ]
