# Generated by Django 3.1.4 on 2021-01-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20210111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='nid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_citations',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_industry_income',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_international_outlook',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_overall',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_research',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='universities',
            name='scores_teaching',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='universities',
            name='stats_female_male_ratio',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='universities',
            name='stats_number_students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universities',
            name='stats_pc_intl_students',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='universities',
            name='stats_student_staff_ratio',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
