# Generated by Django 3.1.4 on 2021-01-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_auto_20210111_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='stats_female_male_ratio',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
