# Generated by Django 3.1.4 on 2021-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20210111_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='url',
        ),
        migrations.AddField(
            model_name='universities',
            name='slug',
            field=models.SlugField(default='not-found'),
        ),
    ]
