# Generated by Django 3.1.4 on 2021-01-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210119_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='posted_on',
        ),
    ]
