# Generated by Django 3.1.4 on 2021-03-22 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210322_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
