# Generated by Django 3.1.4 on 2021-01-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210119_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='https://assets.gopromotional.co.uk/images/article-placeholder.jpg'),
        ),
    ]
