# Generated by Django 3.2.2 on 2021-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='stats_number_students',
            field=models.CharField(max_length=8),
        ),
    ]
