# Generated by Django 3.2.2 on 2021-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_stats_number_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(max_length=85),
        ),
        migrations.AlterField(
            model_name='university',
            name='subjects_offered',
            field=models.TextField(max_length=1000),
        ),
    ]
