# Generated by Django 3.2.2 on 2021-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20210607_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='not-found', max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='subjects_offered',
            field=models.TextField(),
        ),
    ]
